### ISSUE TITLE
State mutation

### ISSUE THREAD

**Issue by conneralegre** [philipeachille/cc-jammming#1]
Important for errors - On line 28 of App.js, you are using `.push` on the `tracks` variable which is actually mutating the state directly because `tracks` is referencing the same value in memory as `this.state.playlistTracks`. We don't want to mutate state directly as this can cause issues with rendering and the data flow of your project. Here is a good stackoverflow thread about this issue: https://stackoverflow.com/questions/23966438/what-is-the-preferred-way-to-mutate-a-react-state

**Comment by philipeachille** [comment]
Changed to concat() method
