### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by conneralegre** [philipeachille/cc-jammming#6]
Grade: **Meets Expectations**

Overall, this project is working great! I really like how clean and easy to read over your code was - this makes it very easy to debug and make additions to. The addition of the `credentials.js` was a really excellent choice in regards to security and is following the best of practices. A couple things I would change is making sure you don't mutate the state directly even if you do not intend to, as those memory references can get pretty tricky! The other thing is making sure include the `reset.css` in order to get the application appearance correct. Next steps, I would attempt to create a feature request for your application, and then taking a shot at implenting it.

Great job!

**Comment by philipeachille** [comment]
Thanks for the feedback
